### ISSUE TITLE
Bug: mirror git task keeps failing only on scheduled builds. manual builds always succeed

### ISSUE THREAD

**Issue by danmorgen** [swellaby/vsts-mirror-git-repository#27]
- **Operating System**: Windows
- **Mirror Git Repository Task version**:  latest for vsts
 
we built a build definition that runs on on-prem build server, and runs mirror tasks to mirror git  repositories from on-prem gitlab to vsts

we use vsts PAT and gitlab PAT for authentication

anytime I triggger build manualy - it succeeds.

I added schedule triggers for nightly activation. nightly always fails

2018-12-03T00:00:19.9218610Z ##[command]git checkout --progress --force refs/remotes/origin/+master
2018-12-03T00:00:19.9547099Z error: pathspec 'refs/remotes/origin/+master' did not match any file(s) known to git.
2018-12-03T00:00:20.0193287Z ##[error]System.InvalidOperationException: Git checkout failed with exit code: 1
   at Agent.Plugins.Repository.GitSourceProvider.GetSourceAsync(AgentTaskPluginExecutionContext executionContext, RepositoryResource repository, CancellationToken cancellationToken)
   at Agent.Plugins.Repository.CheckoutTask.RunAsync(AgentTaskPluginExecutionContext executionContext, CancellationToken token)
   at Agent.PluginHost.Program.Main(String[] args)

**Comment by danmorgen** [comment]
Thanks for the quick response

I'm on a holiday for a week

Adding hila and ondrej

Answers

Get sources goes 100%. It gets the sources but we don't use it because we
mirror


All data correct. Source gitlab onprem using pat, target vsts using pat

Mirror task works 100% on manual trigger, 0% on sched.
Fails on checkout

I even scheduled it 5 min after successful job and it fails

When i return from holiday i plan to create new build which will be
scheduled and will do nothing except triggering this build, so this build
will run as manual

Do you act differently according to trigger type?

**Comment by calebcartwright** [comment]
So the error message you are experiencing in your scheduled build occurs during the system-step for Getting Sources/Checkout (that error does **not** occur during the git mirror task). Based on the provided information, I would imagine that your scheduled build fails immediately on that initial step, and never even gets to the git mirror task.

The git mirror task is just like any other task, it is not involved with VSTS/Azure Pipelines trigger system in anyway nor in the default system steps like `Get sources`.

Since the error isn't occurring in the git mirror task, I'm not sure how much insight we can provide into why the get sources step fails for your scheduled build. One thing I would suggest that you try is using a different linked Azure/VSTS repo for your build pipeline than the one you are using as the destination repo for the mirror task. 

For example, if you want to use the git mirror task to mirror gitlab/repoA to vsts/repoFoo, then I would suggest that in your VSTS pipeline configuration you point to a _third_/different repo (such as vsts/repoBar). Below is an example of one of the pipelines we use for validating the task, where the configured source repo for the pipeline is an empty/random repo we use (named opensource), and then in the mirror task configuration we plug in our respective target source and destination repos for the mirror 

![image](https://user-images.githubusercontent.com/13042488/49479251-f41f5400-f7e7-11e8-9936-dbf4a3f1166d.png)

**Comment by danmorgen** [comment]
No

It happens in mirror task
The task fails on checkout

**Comment by calebcartwright** [comment]
Hi @danmorgen 

The mirror task does **not** perform the checkout and is not involved with it in any way. The checkout is done by a completely different, Microsoft task. When you look at the pipeline logs, you can see a few steps that are performed by the system for all pipelines (and do not come from 3rd party tasks like our git mirror task) such as `prepare job`, and `checkout`. Our code only executes during the `Mirror Git Repository` step:

![image](https://user-images.githubusercontent.com/13042488/49538025-15d41600-f890-11e8-85dc-ee5340b3b545.png)

If you drill into the logs for the `checkout` tasks and look at the details, you will see that it is a **Microsoft** task performing the `git checkout ...` operation

![image](https://user-images.githubusercontent.com/13042488/49538086-3d2ae300-f890-11e8-9261-17fc52061fbe.png)

The git mirror task _only_ performs a `git clone` and `git push` operation, it **never** runs the `git checkout` that you provided from your failing pipeline. `checkout` is only done by the system/Microsoft task:

![image](https://user-images.githubusercontent.com/13042488/49538359-d659f980-f890-11e8-8de9-fe1e50cbf23a.png)

We're happy to help with any errors/questions/etc. that occur _within_ the git mirror task, but it is really difficult for us to offer assistance with issues occurring in a system/Microsoft step that we don't own. 

If you are getting errors _from_ the git mirror task, then please provide the detailed log output from the git mirror task (which should include the header shown above). 

Otherwise if the git checkout error is indeed happening in the checkout task, then I'd again recommend you try implementing the suggestions I shared earlier in the thread:

* link your pipeline sources to a _different_ repository
* make sure you configure your pipeline to clean sources

hope this helps!

**Comment by danmorgen** [comment]
No it didn't help
Unfortunately on vacation so i cannot copy paste log of your failing task

**Comment by danmorgen** [comment]
Sorry my mistake.
Microsoft get sources issues on scheduled build
All apologies

**Comment by calebcartwright** [comment]
No worries! If you haven't had a chance yet, I'd still probably try to switch the repo linked to your build definition. 

If you have any other questions/issues/etc. with the mirror task please let us know!
