### ISSUE TITLE
Q: wondering if you have an example of mirroring to AWS code commit?

### ISSUE THREAD

**Issue by hanxuema** [swellaby/vsts-mirror-git-repository#77]
Q: wondering if you have an example of mirroring to AWS code commit?

**Comment by calebcartwright** [comment]
Hi @hanxuema, no can't say that we do. Are you asking out of curiosity or are you getting an error/failure with a destination target in code commit?

**Comment by houstonhaynes** [comment]
I'm going to jump into this because I'm also having some trouble connecting the dots. AWS CodeCommit generates a user/auth pair for accessing CodeCommit. 

https://docs.aws.amazon.com/codecommit/latest/userguide/setting-up-gc.html

I don't see how the user/password pair relates to PAT

**Comment by calebcartwright** [comment]
Thanks @houstonhaynes!  There's obviously myriad git providers out there, and we really only had a few of the most popular ones available to us for testing. All of the systems we were working with readily supported (and recommended) access tokens as a means of authentication as opposed to username/password, hence the token references in our docs and in the Task input names.

Despite the input name, it's really just the authentication information so if a system you're mirroring from and/or to requires username/password instead of a token then you should just specify that value for the respective `sourceGitRepositoryPersonalAccessToken` and/or `destinationGitRepositoryPersonalAccessToken` with `generated-username:generated-password` (note the separator between user and pass).

A bit of related info can be found in https://github.com/swellaby/vsts-mirror-git-repository/issues/10

**Comment by houstonhaynes** [comment]
Wow - was expecting this to be a message in a bottle to get picked up next week. :)

So I am only slightly ahead of the suggestions - and found that the construction of the user:pass is "confused" by the email

2020-07-04T00:37:21.4077044Z fatal: unable to access 'https://soundfi.com-at-165111528094:***@git-codecommit.us-west-2.amazonaws.com/v1/repos/Hugo-Demo-Web-App/': URL using bad/illegal format or missing URL

**Comment by houstonhaynes** [comment]
Update - switched to a process user I created for Amplify (which of course isn't a name based on an email pattern) and it worked a charm. All good here!

**Comment by calebcartwright** [comment]
> and it worked a charm. All good here!

Excellent! 

> The "soudfi.com" is predecated by myfirstname and @ which seems to be missing from the construct

I think you'd need to uri encode the first `@` if the username portion has that symbol, as the auth info is currently provided the userinfo component of the uri. Guessing something like the below would work

```
houston%40soundfi.com-at-165111528094:password...
```

**Comment by hanxuema** [comment]
Hi, I figured out the way to connect to aws code commit
1. you need to grant the HTTPS Git credentials for AWS CodeCommit
2. use the access key and password. e.g:
key:passowrd

thanks
