### ISSUE TITLE
Q: Clone error "could not read Password for my_git_repo_address"

### ISSUE THREAD

**Issue by redarc** [swellaby/vsts-mirror-git-repository#78]
I have setup PAT for source and target repo, but it always show "could not read Password for my_git_repo_address" while clone repo.

I tried run same command "git.exe -c http.sslVerify=false clone --mirror my_git_repo_address" in my Azure DevOps Agent server, it success clone bare repo. 

Could you review this issue ? 
Thanks a lot.

**Comment by calebcartwright** [comment]
Hi @redarc :wave: We'd be happy to try to help, but unfortunately there's simply not enough information here for us to be able to offer much insight.

Instead of trying to ask questions here in this thread I am going to close this issue and ask you to open a new issue using our Bug template (https://github.com/swellaby/vsts-mirror-git-repository/issues/new?template=01_BUG_TEMPLATE.md) and fill in the relevant details with your context.

Thanks!
